### ISSUE TITLE
UnknownHostException when behind a proxy

### ISSUE THREAD

**Issue by hmnasr** [urbanairship/java-library#52]
I am using version 1.0.0 and proxy configured with 	.setProxyInfo(ProxyInfo.newBuilder().setHost("host").setPassword(password")
						.setPrincipal("user").setPort(port).setProtocol(ProxyInfo.ProxyInfoProtocol.HTTPS)
						.build()

but throw Exception 
java.net.UnknownHostException: go.urbanairship.com: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)

**Comment by pdxmele** [comment]
Hi there, if you're still having problems with this, please contact our support team at https://support.urbanairship.com/ . Thanks!
