### ISSUE TITLE
IllegalStateException in PushDetailResponseReader since 2017-05-22

### ISSUE THREAD

**Issue by ms2scale** [urbanairship/java-library#59]
Our application using 1.0.0 of the api now throws exceptions during report since 2017-05-22:

12:17:50.952 [New I/O worker #1] ERROR c.u.api.client.ResponseAsyncHandler - Exception thrown during response processing
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:49)
	at com.urbanairship.api.reports.parse.PushDetailResponseReader.readPlatforms(PushDetailResponseReader.java:87)
	at com.urbanairship.api.reports.parse.PushDetailResponseDeserializer$1.parse(PushDetailResponseDeserializer.java:87)
	at com.urbanairship.api.reports.parse.PushDetailResponseDeserializer$1.parse(PushDetailResponseDeserializer.java:84)
	at com.urbanairship.api.common.parse.StandardObjectDeserializer.deserialize(StandardObjectDeserializer.java:42)
	at com.urbanairship.api.reports.parse.PushDetailResponseDeserializer.deserialize(PushDetailResponseDeserializer.java:109)
	at com.urbanairship.api.reports.parse.PushDetailResponseDeserializer.deserialize(PushDetailResponseDeserializer.java:20)
...

Changed API version to 1.3.0, same problem. Stacktrace is attached.
[report-exception.txt](https://github.com/urbanairship/java-library/files/1041078/report-exception.txt)

**Comment by pdxmele** [comment]
Hi there, thanks for the report and sorry about that! We'll try to get a fix out very soon.

**Comment by devinsmythe** [comment]
This issue is resolved as of version 1.4.0

**Comment by sarath940** [comment]
I am getting the IllegalState Exception in urban airship SDK after updating the version from 3.0 to 8.8.So Can you please check and let me know why it is coming
this is the log it was coming:::
 java.lang.RuntimeException: Unable to start activity ComponentInfo{act.driverapp/act.driverapp.LoginActivity}: java.lang.IllegalStateException: Take off must be called before shared()

**Comment by pdxmele** [comment]
Hello, please contact our support team at https://support.urbanairship.com for assistance.
